services:
  # Servicename - Full platform run including build phase
  servicename:
    extends:
      file: compose.base.yaml
      service: servicename

networks:
  servicename-network:
    name: servicename-network-dev
    external: false

volumes:
  servicename_logs:
    name: servicename_logs_dev
  servicename_tmp:
    name: servicename_tmp_dev
