# This configuration is intended for development purposes
name: dev-servicename
services:
  sonar:
    container_name: dev-sonarqube
    image: sonarqube:25.3.0.104237-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000

  prometheus:
    image: prom/prometheus:latest
    container_name: dev-prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: dev-grafana
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
