# ===================================================================
# Spring Boot base configuration — overridden by active profile.
# ===================================================================

spring:
  application:
    name: servicename
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized

git:
  build_time: "@git.build.time@"
  commit: "@git.commit.id.abbrev@"
info:
  app:
    build_time: ${git.build_time}
    description: "@project.description@"
    git_commit: ${git.commit}
    name: "@project.name@"
    version: "@project.version@"
